### ISSUE TITLE
remove .val if a reference gets removed

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#45]
seems solid to avoid mem leaks

difficult edge case

b
a.val = 10
aInstance.val = b

now b.set(null)

aInstance.compute() ---> 10

is this logical?

**Comment by marcusbesjes** [comment]
does not seem logical to me, i would not expect it to "revert" like that, but i would expect null

**Comment by jimdebeer** [comment]
null is allready removed so thats weird as well

**Comment by marcusbesjes** [comment]
yeah, but it _is_ a reference to a removed thing.. but yeah it is not removed. i really like that it always cleans up references to things you remove, and im not sure how often i would run into this case where an instance becomes a reference, then reference is removed and it would revert back to its class value.. feels like it will be confuse. 

but still i agree that removing the .val from the is the cleanest, makes most sense so that it doesnt look like the  itself is removed, and in most cases it will just lead to not having .val

i say do it

**Comment by jimdebeer** [comment]
i made it already just that stupid edge case 👹

**Comment by jimdebeer** [comment]
need to conclude this point -- what to set -- can also do empty object for example

**Comment by jimdebeer** [comment]
ok so val.null will not be used as indicator anymore for removed -- will just be null

**Comment by jimdebeer** [comment]
nulled
